### PR TITLE
GetConfigOptionByName has a new argument in PG 9.6

### PR DESCRIPTION
**Pull request by saaros**

### CODE REVIEW

**Comment by dimitri** [comment]
Thanks! Do you want direct push access to the project? I can add you as a project *collaborator* if you want to.

**Comment by saaros** [comment]
I don't mind having push access for merging other people's patches after I've reviewed them, but I'd like someone else to review & merge my commits.

**Comment by dimitri** [comment]
Sure, will continue doing that. You're now a collaborator and may push, welcome to the team and thanks for your time and contributions! ;-)

**Comment by saaros** [comment]
:+1:

**Pull request merged**
